knowage:
    image: guixermo/knowage-server:latest
    links:
        - knowagedb:db
    ports:
        - "8080:8080"
    environment:
        - WAIT_MYSQL=true

knowagedb:
    image: mysql/mysql-server:5.7.24
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
