knowage:
    image: id de la imagen
    links:
        - knowagedb:db
    ports:
        - "62001:62001"
    environment:
        - WAIT_MYSQL=true

knowagedb:
    image: mysql:5.7.24
    environment:
        - MYSQL_USER=knowageuser
        - MYSQL_PASSWORD=knowagepassword
        - MYSQL_DATABASE=knowagedb
        - MYSQL_ROOT_PASSWORD=knowagerootpassword
